# New ICES code for G O Sars - in use from Jan 2021
[NO-SOOP-G__O__Sars]
platform_code = '58G2'
name = 'G.O.Sars'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_GOSars'
category_code = '31'
call_sign = 'LMEL'
creation_date = '2021-01-20T09:24:23Z'
author_list = 'Skjelvan, Ingunn'
NRT = 'True'

	[NO-SOOP-G__O__Sars.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[LMEL]
	platform_id = '58G2'

[NO-SOOP-Nuka__Arctica]
platform_code = "26NA"
name = 'Nuka Arctica'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_26NA'
category_code = '31'
call_sign = 'OXYH2'
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Becker, Meike; Olsen, Are'
NRT = 'True'

	[NO-SOOP-Nuka__Arctica.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OXYH2]
	platform_id = '26NA'

[NO-SOOP-Tukuma__Arctica]
platform_code = "26RA"
name = 'Tukuma Arctica'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_26RA'
category_code = '31'
call_sign = 'OYTR2'
creation_date = '2021-01-01T00:00:00Z'
author_list = 'Becker, Meike; Olsen, Are'
NRT = 'True'

	[NO-SOOP-Tukuma__Arctica.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OYTR2]
	platform_id = '26RA'

[FR-SOOP-France-Brazil]
platform_code = "65DK"
name = 'Cap San Lorenzo'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_VOS%20France-Brazil'
category_code = '32'
call_sign = 'OXOF2'
creation_date = '2019-03-27T14:54:38Z'
author_list = 'Lefèvre, Nathalie'

	[FR-SOOP-France-Brazil.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[OXOF2]
	platform_id = '65DK'


[SailDrone__1030]
platform_code = "SD1030"
name = 'Saildrone 1030'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1030'
category_code = '3B'
call_sign = '5801955'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

	[5801955]
	platform_id = 'SD1030'


[SailDrone__1053]
platform_code = "SD1053"
name = 'Saildrone 1053'
submitter_id = 'OTC_SAILDRONE'
cp_url = 'http://meta.icos-cp.eu/resources/stations/SAILDRONE_SD1053'
category_code = '3B'
call_sign = '1801573'
export = ['ICOS']
creation_date = '2020-03-01T00:00:00Z'
author_list = ''

	[1801573]
	platform_id = 'SD1053'

[BE-SOOP-Simon__Stevin]
platform_code = "11SS"
name = 'Simon Stevin'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_11SS'
category_code = '31'
call_sign = 'ORBS'
creation_date = '2020-09-01T00:00:00Z'
author_list = "Gkritzalis, Thanos; Theetaert, Hannelore; Houthoofdt, Robin; T'Jampens, Michiel"
affiliation = 'Flanders Marine Institute (VLIZ), Wandelaarkaai 7, 8400, Ostend, BE'
NRT = 'True'

	[BE-SOOP-Simon__Stevin.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

	[ORBS]
	platform_id = '11SS'

[BE-FOS-Thornton__Buoy]
platform_code = "1199"
name = 'Thornton Buoy'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_1199'
category_code = '41'
call_sign = ''
creation_date = '2020-09-01T00:00:00Z'
author_list = "Gkritzalis, Thanos; Theetaert, Hannelore; Houthoofdt, Robin; T'Jampens, Michiel"
affiliation = 'Flanders Marine Institute (VLIZ), Wandelaarkaai 7, 8400, Ostend, BE'
NRT = 'True'

	[BE-FOS-Thornton__Buoy.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

[58US]
name = 'Kronprins Haakon'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_58US'
category_code = '31'
call_sign = '3YYQ'
creation_date = '2020-11-17T17:01:34Z'
author_list = 'Fransson, Agneta; Granskog, Mats; Åberg, Petter'
affiliation = 'Norwegian Polar Institute'
NRT = 'False'

	[58US.export]
	NRT = ['ICOS']
	L2 = ['ICOS']

[NO-SOOP-Sea-Cargo__Express]
name = 'Sea-Cargo Express'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_TCarrier'
category_code = '31'
call_sign = '9HA3034'
creation_date = '2023-12-20T15:58:18'
author_list = 'Omar, Abdirahman; de Lange, Tor'
affiliation = 'NORCE Norwegian Research Centre AS'
NRT = 'True'

  [NO-SOOP-Sea-Cargo__Express.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[UK-FOS-PAP]
name = 'Porcupine Abyssal Plain'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_74FS'
category_code = '41'
call_sign = ''
creation_date = '2022-09-27T00:00:00Z'
author_list = 'Hartman, Sue; Lampitt, Richard'
affiliation = 'National Oceanography Centre, UK'
NRT = 'True'

  [UK-FOS-PAP.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[DE-SOOP-Finnmaid]
platform_code = "34FM"
name = 'Finnmaid'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_BALTIC-VOS'
category_code = '31'
call_sign = 'OJMI'
creation_date = '2022-09-27T00:00:00Z'
author_list = 'Glockzin, Michael; Rehder, Gregor'
affiliation = 'Leibniz Institute for Baltic Sea Research'
NRT = 'False'

  [DE-SOOP-Finnmaid.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[IT-FOS-MIRAMARE]
platform_code = '48MB'
name = 'MIRAMARE'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_48MB'
category_code = '41'
call_sign = ''
creation_date = '2024-02-20T16:04:00Z'
author_list = 'Giani, Michele'
affiliation = 'Istituto Nazionale di Oceanografia e di Geofisica Sperimentale'
NRT = 'True'

  [IT-FOS-MIRAMARE.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[ES-SOOP-CanOA]
platform_code = '687B'
name = 'CanOA'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_687B'
category_code = '31'
call_sign = 'CQHZ'
cration_date = '2024-04-05T10:53:00Z'
author_list = 'González-Dávila, Melchor; Santana-Casiano, J. Magdalena'
affiliation = 'Universidad de Las Palmas de Gran Canaria'
NRT = 'True'

  [ES-SOOP-CanOA.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[IT-FOS-W1M3A]
platform_code = '4899'
name = 'W1M3A'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_IT-FOS-W1M3A'
category_code = '41'
call_sign = ''
creation_date = '2024-02-20T16:04:00Z'
author_list = 'Pensieri, Sara;Bozzano, Roberto'
affiliation = 'Consiglio Nazionale delle Ricerche'
NRT = 'False'

  [IT-FOS-W1M3A.export]
  NRT = []
  L2 = ['ICOS']

[IT-FOS-PALOMA]
platform_code = '48MB'
name = 'PALOMA'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_PALOMA'
category_code = '41'
call_sign = ''
creation_date = '2024-02-20T16:04:00Z'
author_list = 'Cantoni, Carolina;Castelli, Giuliano;Luchetta,Anna'
affiliation = 'Istituto di Scienze Marine Trieste'
NRT = 'False'

  [IT-FOS-PALOMA.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

[DE-SOOP-Polarstern]
platform_code = "06AQ"
name = 'Polarstern'
submitter_id = 'OTC'
cp_url = 'http://meta.icos-cp.eu/resources/stations/OS_PS-VOS'
category_code = '31'
call_sign = 'DBLK'
creation_date = '2025-01-17T00:00:00Z'
author_list = 'Hoppema, Mario; van Huevan, Steven;Roden, Nicholas P'
affiliation = 'Alfred-Wegener-Institut Helmholtz-Zentrum für Polar- und Meeresforschung, Bremerhaven'
NRT = 'False'

  [DE-SOOP-Polarstern.export]
  NRT = ['ICOS']
  L2 = ['ICOS']

["SE-FOS-Östergarnsholm"]
platform_code = "77FS"
name = "Östergarnsholm"
submitter_id = 'OTC'
cp_url = "http://meta.icos-cp.eu/resources/stations/OS_SE-FOS-%C3%96stergarnsholm"
category_code = "41"
call_sign = ""
creation_date = "2025-11-21T09:17:40Z"
author_list = "Rutgersson, Anna;Nilsson, Erik;Prytherch, John"
affiliation = "University of Uppsala, Sweden"
NRT = "False"

  ["SE-FOS-Östergarnsholm".export]
  NRT = ['ICOS']
  L2 = ['ICOS']

